name: build-and-publish-lxc
run-name: Build
on: [push]
jobs:
  build-lxc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup distrobuilder"
        run: sudo snap install distrobuilder --classic
        shell: "bash"
      - name: "Setup debootstrap"
        run: sudo apt install debootstrap
        shell: "bash"
      - run: sudo distrobuilder build-lxc debian.yaml
        shell: "bash"
      - run: "mv rootfs.tar.xz grafana-pdc-agent_0.0.19_amd64.tar.gz"
        # See https://cli.github.com/manual/gh_release_create
      - name: Create new release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create v0.0.1 \
          --title "v0.0.1" \
          --generate-notes \
          --target "${{github.sha}}" \
          grafana-pdc-agent_0.0.19_amd64.tar.gz
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"