name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-lxc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup distrobuilder"
        run: sudo snap install distrobuilder --classic
        shell: "bash"
      - name: "Setup debootstrap"
        run: sudo apt install debootstrap
        shell: "bash"
      - run: sudo distrobuilder build-lxc debian.yaml