name: build-and-publish-lxc
run-name: Build
on: [push]
jobs:
  build-lxc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup distrobuilder"
        run: sudo snap install distrobuilder --classic
        shell: "bash"
      - name: "Setup debootstrap"
        run: sudo apt install debootstrap
        shell: "bash"
      - run: sudo distrobuilder build-lxc debian.yaml
        shell: "bash"
      - run: "mv rootfs.tar.xz grafana-pdc-agent_0.0.19_amd64.tar.gz"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: grafana-pdc-agent_0.0.19_amd64.tar.gz